# Generated by Django 5.2.17 on 2026-08-27 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Checklist Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.checklistcategory')),
            ],
            options={
                'ordering': ['order', 'item_name'],
                'unique_together': {('category', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='defects/')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('waiting_for_reinspection', 'Waiting for Reinspection'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('assigned_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='inspections.checklistcategory')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='projects.unit')),
            ],
        ),
        migrations.CreateModel(
            name='DefectActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='inspections.defect')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('internal', 'Internal'), ('customer', 'Customer')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_inspections', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='projects.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitInspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('not_inspected', 'Not Inspected'), ('passed', 'Passed'), ('defect_found', 'Defect Found'), ('not_applicable', 'Not Applicable'), ('resolved', 'Resolved')], default='not_inspected', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_results', to='inspections.checklistitem')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspections.unitinspection')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='inspection_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='inspections.unitinspectionresult'),
        ),
        migrations.AddConstraint(
            model_name='unitinspectionresult',
            constraint=models.UniqueConstraint(fields=('inspection', 'checklist_item'), name='unique_inspection_checklist_item'),
        ),
    ]
