# Generated by Django 5.2.17 on 2026-09-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='resolution_evidence',
            field=models.FileField(blank=True, null=True, upload_to='defects/evidence/'),
        ),
        migrations.AddField(
            model_name='defect',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='defects/videos/'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='defects/photos/'),
        ),
    ]
