# Generated by Django 5.2.17 on 2026-09-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_defect_resolution_evidence_defect_video_and_more'),
        ('platform_admin', '0002_subscriptionbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitinspection',
            name='platform_checklist',
            field=models.ForeignKey(blank=True, help_text='The Super Admin standard checklist used as a template for this inspection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='platform_admin.checklist'),
        ),
    ]
