# Generated by Django 5.2.17 on 2026-09-11 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0003_add_platform_checklist"),
        ("platform_admin", "0003_storage_limits"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="checklistitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="checklistitem",
            name="category",
        ),
        migrations.AlterField(
            model_name="defect",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Category of the defect (e.g., Plumbing, Electrical).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="unitinspectionresult",
            name="checklist_item",
        ),
        migrations.AddField(
            model_name="unitinspectionresult",
            name="checklist_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspection_results",
                to="platform_admin.checklistitem",
            ),
        ),
        migrations.AddField(
            model_name="unitinspectionresult",
            name="snapshot_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="unitinspectionresult",
            name="snapshot_item_text",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name="ChecklistCategory",
        ),
        migrations.DeleteModel(
            name="ChecklistItem",
        ),
    ]
