# Generated by Django 5.2.17 on 2026-09-11 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_remove_checklistitem_category_alter_defect_category_and_more'),
        ('platform_admin', '0004_remove_checklistitem_checklist'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='unitinspectionresult',
        #     name='unique_inspection_checklist_item',
        # ),
        migrations.RemoveField(
            model_name='unitinspection',
            name='platform_checklist',
        ),
        migrations.RemoveField(
            model_name='unitinspectionresult',
            name='checklist_item',
        ),
        migrations.AddField(
            model_name='unitinspectionresult',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_results', to='platform_admin.checklist'),
        ),
        migrations.AddConstraint(
            model_name='unitinspectionresult',
            constraint=models.UniqueConstraint(fields=('inspection', 'checklist'), name='unique_inspection_checklist'),
        ),
    ]
