# Generated by Django 5.2.17 on 2026-08-27 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='projects.block')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('commercial', 'Commercial'), ('mixed_use', 'Mixed Use')], max_length=20)),
                ('address', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('rera_number', models.CharField(blank=True, max_length=100)),
                ('builder_contact', models.CharField(blank=True, max_length=150)),
                ('common_facilities', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('nearing_completion', 'Nearing Completion'), ('inspection_stage', 'Inspection Stage'), ('customer_handover_stage', 'Customer Handover Stage'), ('warranty_stage', 'Warranty Stage'), ('association_handover_stage', 'Association Handover Stage'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.project'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('parking_details', models.CharField(blank=True, max_length=200)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('expected_handover_date', models.DateField(blank=True, null=True)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('construction_in_progress', 'Construction in Progress'), ('nearing_completion', 'Nearing Completion'), ('internal_inspection', 'Internal Inspection'), ('defect_resolution', 'Defect Resolution'), ('customer_inspection_ready', 'Customer Inspection Ready'), ('customer_inspection_completed', 'Customer Inspection Completed'), ('handover_preparation', 'Handover Preparation'), ('ready_for_handover', 'Ready for Handover'), ('handover_scheduled', 'Handover Scheduled'), ('handed_over', 'Handed Over'), ('warranty_stage', 'Warranty Stage')], default='not_started', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_units', to=settings.AUTH_USER_MODEL)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.floor')),
            ],
        ),
    ]
