# Generated by Django 5.2.17 on 2026-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_builder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='block',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='floor',
            name='floor_number',
            field=models.IntegerField(default=0),
        ),
    ]
