# Generated by Django 5.2.17 on 2026-09-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_image_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
