# Generated by Django 5.2.17 on 2026-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_unit_bathrooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type_other",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("commercial", "Commercial"),
                    ("mixed_use", "Mixed Use"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
