# Generated by Django 5.2.17 on 2026-09-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_project_type_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='parking_details',
        ),
    ]
