--
-- PostgreSQL database dump
--

\restrict tp8HHDTXamCBp752aMJ1v2iNBkavlB3l7nmZ2ESV8GFMJ1ztb82iK5kctGxXpFM

-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO handoverly;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO handoverly;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO handoverly;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.auth_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO handoverly;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO handoverly;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO handoverly;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO handoverly;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO handoverly;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO handoverly;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO handoverly;

--
-- Name: inspections_checklistcategory; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.inspections_checklistcategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT inspections_checklistcategory_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.inspections_checklistcategory OWNER TO handoverly;

--
-- Name: inspections_checklistcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.inspections_checklistcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspections_checklistcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inspections_checklistitem; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.inspections_checklistitem (
    id bigint NOT NULL,
    item_name character varying(255) NOT NULL,
    "order" integer NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT inspections_checklistitem_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.inspections_checklistitem OWNER TO handoverly;

--
-- Name: inspections_checklistitem_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.inspections_checklistitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspections_checklistitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inspections_defect; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.inspections_defect (
    id bigint NOT NULL,
    description text NOT NULL,
    photo character varying(100),
    priority character varying(20) NOT NULL,
    status character varying(30) NOT NULL,
    reported_date timestamp with time zone NOT NULL,
    expected_completion_date date,
    resolved_date date,
    reopen_reason text,
    assigned_contractor_id bigint,
    category_id bigint,
    reported_by_id bigint,
    unit_id bigint NOT NULL,
    inspection_result_id bigint
);


ALTER TABLE public.inspections_defect OWNER TO handoverly;

--
-- Name: inspections_defect_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.inspections_defect ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspections_defect_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inspections_defectactivitylog; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.inspections_defectactivitylog (
    id bigint NOT NULL,
    action character varying(100) NOT NULL,
    remarks text,
    "timestamp" timestamp with time zone NOT NULL,
    defect_id bigint NOT NULL,
    performed_by_id bigint
);


ALTER TABLE public.inspections_defectactivitylog OWNER TO handoverly;

--
-- Name: inspections_defectactivitylog_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.inspections_defectactivitylog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspections_defectactivitylog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inspections_unitinspection; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.inspections_unitinspection (
    id bigint NOT NULL,
    inspection_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    scheduled_date date,
    completed_date date,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    inspected_by_id bigint,
    unit_id bigint NOT NULL
);


ALTER TABLE public.inspections_unitinspection OWNER TO handoverly;

--
-- Name: inspections_unitinspection_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.inspections_unitinspection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspections_unitinspection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inspections_unitinspectionresult; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.inspections_unitinspectionresult (
    id bigint NOT NULL,
    result character varying(30) NOT NULL,
    remarks text,
    checklist_item_id bigint NOT NULL,
    inspection_id bigint NOT NULL
);


ALTER TABLE public.inspections_unitinspectionresult OWNER TO handoverly;

--
-- Name: inspections_unitinspectionresult_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.inspections_unitinspectionresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspections_unitinspectionresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_block; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.projects_block (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL
);


ALTER TABLE public.projects_block OWNER TO handoverly;

--
-- Name: projects_block_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.projects_block ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_block_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_floor; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.projects_floor (
    id bigint NOT NULL,
    floor_number integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    block_id bigint NOT NULL
);


ALTER TABLE public.projects_floor OWNER TO handoverly;

--
-- Name: projects_floor_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.projects_floor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_floor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_project; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.projects_project (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    project_type character varying(20) NOT NULL,
    address text NOT NULL,
    start_date date,
    expected_completion_date date,
    rera_number character varying(100) NOT NULL,
    builder_contact character varying(150) NOT NULL,
    common_facilities text NOT NULL,
    status character varying(30) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    project_manager_id bigint
);


ALTER TABLE public.projects_project OWNER TO handoverly;

--
-- Name: projects_project_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.projects_project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: projects_unit; Type: TABLE; Schema: public; Owner: handoverly
--

CREATE TABLE public.projects_unit (
    id bigint NOT NULL,
    unit_number character varying(20) NOT NULL,
    unit_type character varying(50) NOT NULL,
    area_sqft numeric(10,2),
    bedrooms integer,
    parking_details character varying(200) NOT NULL,
    booking_date date,
    agreement_date date,
    expected_handover_date date,
    completion_percentage integer NOT NULL,
    status character varying(40) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    customer_id bigint,
    floor_id bigint NOT NULL
);


ALTER TABLE public.projects_unit OWNER TO handoverly;

--
-- Name: projects_unit_id_seq; Type: SEQUENCE; Schema: public; Owner: handoverly
--

ALTER TABLE public.projects_unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add User	6	add_user
22	Can change User	6	change_user
23	Can delete User	6	delete_user
24	Can view User	6	view_user
25	Can add block	7	add_block
26	Can change block	7	change_block
27	Can delete block	7	delete_block
28	Can view block	7	view_block
29	Can add floor	8	add_floor
30	Can change floor	8	change_floor
31	Can delete floor	8	delete_floor
32	Can view floor	8	view_floor
33	Can add project	9	add_project
34	Can change project	9	change_project
35	Can delete project	9	delete_project
36	Can view project	9	view_project
37	Can add unit	10	add_unit
38	Can change unit	10	change_unit
39	Can delete unit	10	delete_unit
40	Can view unit	10	view_unit
41	Can add checklist category	11	add_checklistcategory
42	Can change checklist category	11	change_checklistcategory
43	Can delete checklist category	11	delete_checklistcategory
44	Can view checklist category	11	view_checklistcategory
45	Can add checklist item	12	add_checklistitem
46	Can change checklist item	12	change_checklistitem
47	Can delete checklist item	12	delete_checklistitem
48	Can view checklist item	12	view_checklistitem
49	Can add defect	13	add_defect
50	Can change defect	13	change_defect
51	Can delete defect	13	delete_defect
52	Can view defect	13	view_defect
53	Can add defect activity log	14	add_defectactivitylog
54	Can change defect activity log	14	change_defectactivitylog
55	Can delete defect activity log	14	delete_defectactivitylog
56	Can view defect activity log	14	view_defectactivitylog
57	Can add unit inspection	15	add_unitinspection
58	Can change unit inspection	15	change_unitinspection
59	Can delete unit inspection	15	delete_unitinspection
60	Can view unit inspection	15	view_unitinspection
61	Can add unit inspection result	16	add_unitinspectionresult
62	Can change unit inspection result	16	change_unitinspectionresult
63	Can delete unit inspection result	16	delete_unitinspectionresult
64	Can view unit inspection result	16	view_unitinspectionresult
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$sN8ZSio8omxPV7wXCmysNc$1/RxlssCNvrUjB0VzUiVtcEnwvjEAZu19VAIJklUeoo=	2026-08-27 05:25:01.230716+00	t	admin@handoverly.com			admin@handoverly.com	t	t	2026-08-27 05:09:58.052362+00
2	pbkdf2_sha256$1000000$wUTO5MS7c6zYzcHLp7H29B$JiV4Qyf1QbOJ80u66170CNHYly2BbF3W1A5ot+LxgGE=	2026-08-27 05:31:02.630979+00	t	testuser@handoverly.com			testuser@handoverly.com	t	t	2026-08-27 05:30:01+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-27 05:30:01.703808+00	2	testuser@handoverly.com	1	[{"added": {}}]	6	1
2	2026-08-27 05:30:20.643791+00	2	testuser@handoverly.com	2	[{"changed": {"fields": ["Email address", "Staff status", "Superuser status"]}}]	6	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	projects	block
8	projects	floor
9	projects	project
10	projects	unit
11	inspections	checklistcategory
12	inspections	checklistitem
13	inspections	defect
14	inspections	defectactivitylog
15	inspections	unitinspection
16	inspections	unitinspectionresult
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-27 05:09:50.230088+00
2	contenttypes	0002_remove_content_type_name	2026-08-27 05:09:50.246121+00
3	auth	0001_initial	2026-08-27 05:09:50.299688+00
4	auth	0002_alter_permission_name_max_length	2026-08-27 05:09:50.305409+00
5	auth	0003_alter_user_email_max_length	2026-08-27 05:09:50.311426+00
6	auth	0004_alter_user_username_opts	2026-08-27 05:09:50.319025+00
7	auth	0005_alter_user_last_login_null	2026-08-27 05:09:50.327472+00
8	auth	0006_require_contenttypes_0002	2026-08-27 05:09:50.332412+00
9	auth	0007_alter_validators_add_error_messages	2026-08-27 05:09:50.340188+00
10	auth	0008_alter_user_username_max_length	2026-08-27 05:09:50.348028+00
11	auth	0009_alter_user_last_name_max_length	2026-08-27 05:09:50.355852+00
12	auth	0010_alter_group_name_max_length	2026-08-27 05:09:50.367578+00
13	auth	0011_update_proxy_permissions	2026-08-27 05:09:50.374932+00
14	auth	0012_alter_user_first_name_max_length	2026-08-27 05:09:50.383157+00
15	accounts	0001_initial	2026-08-27 05:09:50.448573+00
16	admin	0001_initial	2026-08-27 05:09:50.479721+00
17	admin	0002_logentry_remove_auto_add	2026-08-27 05:09:50.4882+00
18	admin	0003_logentry_add_action_flag_choices	2026-08-27 05:09:50.499439+00
19	projects	0001_initial	2026-08-27 05:09:50.585862+00
20	inspections	0001_initial	2026-08-27 05:09:50.751086+00
21	sessions	0001_initial	2026-08-27 05:09:50.767798+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
o3qq9lly69zkwhxnrbp8onaxssx8ikgm	.eJxVjMsOwiAQRf-FtSFQGB4u3fsNZGBAqgaS0q6M_65NutDtPefcFwu4rTVsIy9hJnZmEzv9bhHTI7cd0B3brfPU27rMke8KP-jg1075eTncv4OKo35rbbwTSmI2BoWWRgOS9DFPBFZmQEkCnLekycuoIKmCxSontItQjDfs_QHA4Tcd:1wzSha:bwmcGtQtMRv2IGGvXj1QX1dMTa-1hp8qXA6HAwWMzV8	2026-09-10 05:31:02.634497+00
\.


--
-- Data for Name: inspections_checklistcategory; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.inspections_checklistcategory (id, name, "order") FROM stdin;
\.


--
-- Data for Name: inspections_checklistitem; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.inspections_checklistitem (id, item_name, "order", category_id) FROM stdin;
\.


--
-- Data for Name: inspections_defect; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.inspections_defect (id, description, photo, priority, status, reported_date, expected_completion_date, resolved_date, reopen_reason, assigned_contractor_id, category_id, reported_by_id, unit_id, inspection_result_id) FROM stdin;
\.


--
-- Data for Name: inspections_defectactivitylog; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.inspections_defectactivitylog (id, action, remarks, "timestamp", defect_id, performed_by_id) FROM stdin;
\.


--
-- Data for Name: inspections_unitinspection; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.inspections_unitinspection (id, inspection_type, status, scheduled_date, completed_date, created_at, updated_at, inspected_by_id, unit_id) FROM stdin;
\.


--
-- Data for Name: inspections_unitinspectionresult; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.inspections_unitinspectionresult (id, result, remarks, checklist_item_id, inspection_id) FROM stdin;
\.


--
-- Data for Name: projects_block; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.projects_block (id, name, created_at, project_id) FROM stdin;
\.


--
-- Data for Name: projects_floor; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.projects_floor (id, floor_number, created_at, block_id) FROM stdin;
\.


--
-- Data for Name: projects_project; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.projects_project (id, name, project_type, address, start_date, expected_completion_date, rera_number, builder_contact, common_facilities, status, created_at, updated_at, created_by_id, project_manager_id) FROM stdin;
\.


--
-- Data for Name: projects_unit; Type: TABLE DATA; Schema: public; Owner: handoverly
--

COPY public.projects_unit (id, unit_number, unit_type, area_sqft, bedrooms, parking_details, booking_date, agreement_date, expected_handover_date, completion_percentage, status, created_at, updated_at, customer_id, floor_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 2, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 21, true);


--
-- Name: inspections_checklistcategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.inspections_checklistcategory_id_seq', 1, false);


--
-- Name: inspections_checklistitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.inspections_checklistitem_id_seq', 1, false);


--
-- Name: inspections_defect_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.inspections_defect_id_seq', 1, false);


--
-- Name: inspections_defectactivitylog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.inspections_defectactivitylog_id_seq', 1, false);


--
-- Name: inspections_unitinspection_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.inspections_unitinspection_id_seq', 1, false);


--
-- Name: inspections_unitinspectionresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.inspections_unitinspectionresult_id_seq', 1, false);


--
-- Name: projects_block_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.projects_block_id_seq', 1, false);


--
-- Name: projects_floor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.projects_floor_id_seq', 1, false);


--
-- Name: projects_project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.projects_project_id_seq', 1, false);


--
-- Name: projects_unit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: handoverly
--

SELECT pg_catalog.setval('public.projects_unit_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: inspections_checklistcategory inspections_checklistcategory_name_key; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_checklistcategory
    ADD CONSTRAINT inspections_checklistcategory_name_key UNIQUE (name);


--
-- Name: inspections_checklistcategory inspections_checklistcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_checklistcategory
    ADD CONSTRAINT inspections_checklistcategory_pkey PRIMARY KEY (id);


--
-- Name: inspections_checklistitem inspections_checklistitem_category_id_item_name_1961356c_uniq; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_checklistitem
    ADD CONSTRAINT inspections_checklistitem_category_id_item_name_1961356c_uniq UNIQUE (category_id, item_name);


--
-- Name: inspections_checklistitem inspections_checklistitem_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_checklistitem
    ADD CONSTRAINT inspections_checklistitem_pkey PRIMARY KEY (id);


--
-- Name: inspections_defect inspections_defect_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defect
    ADD CONSTRAINT inspections_defect_pkey PRIMARY KEY (id);


--
-- Name: inspections_defectactivitylog inspections_defectactivitylog_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defectactivitylog
    ADD CONSTRAINT inspections_defectactivitylog_pkey PRIMARY KEY (id);


--
-- Name: inspections_unitinspection inspections_unitinspection_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_unitinspection
    ADD CONSTRAINT inspections_unitinspection_pkey PRIMARY KEY (id);


--
-- Name: inspections_unitinspectionresult inspections_unitinspectionresult_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_unitinspectionresult
    ADD CONSTRAINT inspections_unitinspectionresult_pkey PRIMARY KEY (id);


--
-- Name: projects_block projects_block_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_block
    ADD CONSTRAINT projects_block_pkey PRIMARY KEY (id);


--
-- Name: projects_floor projects_floor_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_floor
    ADD CONSTRAINT projects_floor_pkey PRIMARY KEY (id);


--
-- Name: projects_project projects_project_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_pkey PRIMARY KEY (id);


--
-- Name: projects_unit projects_unit_pkey; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_unit
    ADD CONSTRAINT projects_unit_pkey PRIMARY KEY (id);


--
-- Name: inspections_unitinspectionresult unique_inspection_checklist_item; Type: CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_unitinspectionresult
    ADD CONSTRAINT unique_inspection_checklist_item UNIQUE (inspection_id, checklist_item_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: inspections_checklistcategory_name_22763b36_like; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_checklistcategory_name_22763b36_like ON public.inspections_checklistcategory USING btree (name varchar_pattern_ops);


--
-- Name: inspections_checklistitem_category_id_f642a489; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_checklistitem_category_id_f642a489 ON public.inspections_checklistitem USING btree (category_id);


--
-- Name: inspections_defect_assigned_contractor_id_0c4d70fe; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_defect_assigned_contractor_id_0c4d70fe ON public.inspections_defect USING btree (assigned_contractor_id);


--
-- Name: inspections_defect_category_id_955d6890; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_defect_category_id_955d6890 ON public.inspections_defect USING btree (category_id);


--
-- Name: inspections_defect_inspection_result_id_17d88ec9; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_defect_inspection_result_id_17d88ec9 ON public.inspections_defect USING btree (inspection_result_id);


--
-- Name: inspections_defect_reported_by_id_361389b5; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_defect_reported_by_id_361389b5 ON public.inspections_defect USING btree (reported_by_id);


--
-- Name: inspections_defect_unit_id_59adc226; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_defect_unit_id_59adc226 ON public.inspections_defect USING btree (unit_id);


--
-- Name: inspections_defectactivitylog_defect_id_6e30576b; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_defectactivitylog_defect_id_6e30576b ON public.inspections_defectactivitylog USING btree (defect_id);


--
-- Name: inspections_defectactivitylog_performed_by_id_c47053b3; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_defectactivitylog_performed_by_id_c47053b3 ON public.inspections_defectactivitylog USING btree (performed_by_id);


--
-- Name: inspections_unitinspection_inspected_by_id_d99b5dd5; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_unitinspection_inspected_by_id_d99b5dd5 ON public.inspections_unitinspection USING btree (inspected_by_id);


--
-- Name: inspections_unitinspection_unit_id_362eb4ce; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_unitinspection_unit_id_362eb4ce ON public.inspections_unitinspection USING btree (unit_id);


--
-- Name: inspections_unitinspectionresult_checklist_item_id_9f1393a6; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_unitinspectionresult_checklist_item_id_9f1393a6 ON public.inspections_unitinspectionresult USING btree (checklist_item_id);


--
-- Name: inspections_unitinspectionresult_inspection_id_a2b94817; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX inspections_unitinspectionresult_inspection_id_a2b94817 ON public.inspections_unitinspectionresult USING btree (inspection_id);


--
-- Name: projects_block_project_id_91b2039f; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX projects_block_project_id_91b2039f ON public.projects_block USING btree (project_id);


--
-- Name: projects_floor_block_id_7d506d82; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX projects_floor_block_id_7d506d82 ON public.projects_floor USING btree (block_id);


--
-- Name: projects_project_created_by_id_c49d7b6d; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX projects_project_created_by_id_c49d7b6d ON public.projects_project USING btree (created_by_id);


--
-- Name: projects_project_project_manager_id_39466ecc; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX projects_project_project_manager_id_39466ecc ON public.projects_project USING btree (project_manager_id);


--
-- Name: projects_unit_customer_id_943e9da1; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX projects_unit_customer_id_943e9da1 ON public.projects_unit USING btree (customer_id);


--
-- Name: projects_unit_floor_id_bf117d24; Type: INDEX; Schema: public; Owner: handoverly
--

CREATE INDEX projects_unit_floor_id_bf117d24 ON public.projects_unit USING btree (floor_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_checklistitem inspections_checklis_category_id_f642a489_fk_inspectio; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_checklistitem
    ADD CONSTRAINT inspections_checklis_category_id_f642a489_fk_inspectio FOREIGN KEY (category_id) REFERENCES public.inspections_checklistcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_defect inspections_defect_assigned_contractor__0c4d70fe_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defect
    ADD CONSTRAINT inspections_defect_assigned_contractor__0c4d70fe_fk_auth_user FOREIGN KEY (assigned_contractor_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_defect inspections_defect_category_id_955d6890_fk_inspectio; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defect
    ADD CONSTRAINT inspections_defect_category_id_955d6890_fk_inspectio FOREIGN KEY (category_id) REFERENCES public.inspections_checklistcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_defect inspections_defect_inspection_result_id_17d88ec9_fk_inspectio; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defect
    ADD CONSTRAINT inspections_defect_inspection_result_id_17d88ec9_fk_inspectio FOREIGN KEY (inspection_result_id) REFERENCES public.inspections_unitinspectionresult(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_defect inspections_defect_reported_by_id_361389b5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defect
    ADD CONSTRAINT inspections_defect_reported_by_id_361389b5_fk_auth_user_id FOREIGN KEY (reported_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_defect inspections_defect_unit_id_59adc226_fk_projects_unit_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defect
    ADD CONSTRAINT inspections_defect_unit_id_59adc226_fk_projects_unit_id FOREIGN KEY (unit_id) REFERENCES public.projects_unit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_defectactivitylog inspections_defectac_defect_id_6e30576b_fk_inspectio; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defectactivitylog
    ADD CONSTRAINT inspections_defectac_defect_id_6e30576b_fk_inspectio FOREIGN KEY (defect_id) REFERENCES public.inspections_defect(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_defectactivitylog inspections_defectac_performed_by_id_c47053b3_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_defectactivitylog
    ADD CONSTRAINT inspections_defectac_performed_by_id_c47053b3_fk_auth_user FOREIGN KEY (performed_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_unitinspectionresult inspections_unitinsp_checklist_item_id_9f1393a6_fk_inspectio; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_unitinspectionresult
    ADD CONSTRAINT inspections_unitinsp_checklist_item_id_9f1393a6_fk_inspectio FOREIGN KEY (checklist_item_id) REFERENCES public.inspections_checklistitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_unitinspection inspections_unitinsp_inspected_by_id_d99b5dd5_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_unitinspection
    ADD CONSTRAINT inspections_unitinsp_inspected_by_id_d99b5dd5_fk_auth_user FOREIGN KEY (inspected_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_unitinspectionresult inspections_unitinsp_inspection_id_a2b94817_fk_inspectio; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_unitinspectionresult
    ADD CONSTRAINT inspections_unitinsp_inspection_id_a2b94817_fk_inspectio FOREIGN KEY (inspection_id) REFERENCES public.inspections_unitinspection(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: inspections_unitinspection inspections_unitinspection_unit_id_362eb4ce_fk_projects_unit_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.inspections_unitinspection
    ADD CONSTRAINT inspections_unitinspection_unit_id_362eb4ce_fk_projects_unit_id FOREIGN KEY (unit_id) REFERENCES public.projects_unit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_block projects_block_project_id_91b2039f_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_block
    ADD CONSTRAINT projects_block_project_id_91b2039f_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_floor projects_floor_block_id_7d506d82_fk_projects_block_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_floor
    ADD CONSTRAINT projects_floor_block_id_7d506d82_fk_projects_block_id FOREIGN KEY (block_id) REFERENCES public.projects_block(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_created_by_id_c49d7b6d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_created_by_id_c49d7b6d_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_project projects_project_project_manager_id_39466ecc_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_project_manager_id_39466ecc_fk_auth_user_id FOREIGN KEY (project_manager_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_unit projects_unit_customer_id_943e9da1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_unit
    ADD CONSTRAINT projects_unit_customer_id_943e9da1_fk_auth_user_id FOREIGN KEY (customer_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: projects_unit projects_unit_floor_id_bf117d24_fk_projects_floor_id; Type: FK CONSTRAINT; Schema: public; Owner: handoverly
--

ALTER TABLE ONLY public.projects_unit
    ADD CONSTRAINT projects_unit_floor_id_bf117d24_fk_projects_floor_id FOREIGN KEY (floor_id) REFERENCES public.projects_floor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict tp8HHDTXamCBp752aMJ1v2iNBkavlB3l7nmZ2ESV8GFMJ1ztb82iK5kctGxXpFM

