# Generated by Django 5.2.17 on 2026-09-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0002_subscriptionbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='storage_limit_gb',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
