# Generated by Django 5.2.17 on 2026-09-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_storage_limits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
    ]
