# Generated by Django 5.2.17 on 2026-09-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_remove_unitinspectionresult_unique_inspection_checklist_item_and_more'),
        ('platform_admin', '0004_remove_checklistitem_checklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
    ]
