# Generated by Django 5.2.17 on 2026-09-04 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('registered_address', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('business_registration_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_builder', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builders', to='platform_admin.subscriptionplan')),
            ],
            options={
                'db_table': 'builders_builder_company',
            },
        ),
    ]
