# Generated by Django 5.2.17 on 2026-09-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildercompany',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
