# Generated by Django 5.2.17 on 2026-09-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BUILDER_OWNER', 'Builder Owner'), ('CUSTOMER', 'Customer'), ('CONTRACTOR', 'Contractor'), ('ACCOUNTS', 'Accounts'), ('CRM', 'CRM')], default='CUSTOMER', max_length=50),
        ),
    ]
