# Generated by Django 5.2.17 on 2026-09-07 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('builders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='builder_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='builders.buildercompany'),
        ),
    ]
