# Generated by Django 5.2.17 on 2026-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_builder_company'),
        ('projects', '0002_project_builder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_staff', to='projects.project'),
        ),
    ]
