# Generated by Django 5.2.17 on 2026-09-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trade',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
