# Generated by Django 5.2.17 on 2026-09-12 09:02

import logging
from django.db import migrations

def deactivate_pm_and_crm(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Find PM and CRM users
    users_to_migrate = User.objects.filter(role__in=['PROJECT_MANAGER', 'CRM'])
    
    count = 0
    for user in users_to_migrate:
        user.is_active = False
        user.role = 'CUSTOMER' # Fallback to lowest privilege to pass future validation
        user.save(update_fields=['is_active', 'role'])
        count += 1
        
    if count > 0:
        logging.info(f"Deactivated {count} deprecated PROJECT_MANAGER/CRM users.")

def reverse_deactivate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_trade'),
    ]

    operations = [
        migrations.RunPython(deactivate_pm_and_crm, reverse_deactivate),
    ]
