# Generated by Django 5.2.17 on 2026-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_pm_crm_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BUILDER_OWNER', 'Builder Owner'), ('PROJECT_ADMIN', 'Project Admin'), ('SITE_ENGINEER', 'Site Engineer'), ('ACCOUNTS', 'Accounts'), ('CONTRACTOR', 'Contractor'), ('CUSTOMER', 'Customer'), ('ASSOCIATION_REPRESENTATIVE', 'Association Representative')], default='CUSTOMER', max_length=50),
        ),
    ]
