# Generated by Django 5.2.17 on 2026-09-09 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builders', '0001_initial'),
        ('inspections', '0002_defect_resolution_evidence_defect_video_and_more'),
        ('projects', '0004_project_image_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('PROJECT_DOC', 'Project Document'), ('CUSTOMER_DOC', 'Customer Document'), ('DEFECT_EVIDENCE', 'Defect Evidence'), ('WARRANTY', 'Warranty Document'), ('RECEIPT', 'Payment Receipt'), ('HANDOVER_CERT', 'Handover Certificate'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUIRED', 'Required'), ('REQUESTED', 'Requested'), ('UPLOADED', 'Uploaded'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('NOT_APPLICABLE', 'Not Applicable')], default='APPROVED', max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builder_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='builders.buildercompany')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_documents', to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_documents', to='inspections.defect')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.unit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
