# Generated by Django 5.2.17 on 2026-09-09 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builders', '0001_initial'),
        ('projects', '0004_project_image_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(default='Initial Planning', max_length=100)),
                ('structure_status', models.CharField(default='Pending', max_length=50)),
                ('docs_status', models.CharField(default='Pending', max_length=50)),
                ('financials_status', models.CharField(default='Pending', max_length=50)),
                ('assets_status', models.CharField(default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builder_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_transitions', to='builders.buildercompany')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_transitions', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='HandoverRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_READY', 'Not Ready'), ('READY_FOR_HANDOVER', 'Ready for Handover'), ('HANDOVER_SCHEDULED', 'Handover Scheduled'), ('HANDED_OVER', 'Handed Over')], default='NOT_READY', max_length=50)),
                ('meter_readings', models.TextField(blank=True, default='Electricity: 0, Water: 0')),
                ('keys_handed_over', models.BooleanField(default=False)),
                ('access_cards_handed_over', models.BooleanField(default=False)),
                ('parking_allotted', models.CharField(blank=True, max_length=100)),
                ('customer_signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('handover_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('site_engineer_approval', models.BooleanField(default=False)),
                ('project_manager_approval', models.BooleanField(default=False)),
                ('crm_approval', models.BooleanField(default=False)),
                ('accounts_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to=settings.AUTH_USER_MODEL)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_record', to='projects.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('maintenance_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('corpus_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('registration_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('utility_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('additional_work_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('late_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refundable_deposits', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('NOT_REVIEWED', 'Not Reviewed'), ('PENDING_PAYMENT', 'Pending Payment'), ('PARTIALLY_CLEARED', 'Partially Cleared'), ('CLEARED', 'Cleared'), ('APPROVED_FOR_HANDOVER', 'Approved for Handover'), ('ON_HOLD', 'On Hold')], default='NOT_REVIEWED', max_length=50)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.unit')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(default='General Warranty', max_length=100)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='care_evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='projects.unit')),
            ],
        ),
    ]
