# Generated by Django 5.2.17 on 2026-09-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handovers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverrecord',
            name='parking_allotted',
        ),
    ]
