# Generated by Django 5.2.17 on 2026-09-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handovers', '0002_remove_handoverrecord_parking_allotted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverrecord',
            name='crm_approval',
        ),
        migrations.RemoveField(
            model_name='handoverrecord',
            name='project_manager_approval',
        ),
    ]
