# Generated by Django 5.2.17 on 2026-09-12 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handovers', '0003_remove_handoverrecord_crm_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('BOOKING_AMOUNT', 'Booking Amount'), ('AGREEMENT_AMOUNT', 'Agreement Amount'), ('INSTALLMENT', 'Installment'), ('MAINTENANCE_DEPOSIT', 'Maintenance Deposit'), ('CORPUS_FUND', 'Corpus Fund'), ('REGISTRATION', 'Registration'), ('UTILITY_CHARGE', 'Utility Charge'), ('ADDITIONAL_CHARGE', 'Additional Charge'), ('LATE_FEE', 'Late Fee'), ('OTHER', 'Other')], default='INSTALLMENT', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='handovers.paymentclearance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('ONLINE', 'Online Payment Gateway'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='handovers.charge')),
                ('clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='handovers.paymentclearance')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
